language: csharp
mono: none
dotnet: 2.1.104
solution: BitStringLibrary/BitStringLibrary.sln
script:
 - cd BitStringLibrary
 - dotnet restore
 - dotnet test test/BitString.Test
 - dotnet test test/HexString.Test