language: csharp
mono: none
dotnet: 2.1.104
solution: BitStringLibrary/BitStringLibrary.sln
script:
 - dotnet restore
 - dotnet test BitStringLibrary/test/BitString.Test
 - dotnet test BitStringLibrary/test/HexString.Test
 - dotnet test WebApi/tests